version: "3.7"
services:
  db:
    image: postgres:15
    container_name: ${POSTGRES_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    command: ["/src/docker/db_data.sh"]
    ports:
      - ${FASTAPI_PORT}
    depends_on:
      - db
    env_file:
      - .env
